version: '3'
services:
  nginx:
    container_name: 'nginx'
    image: nginx:1.14
    links:
      - php
  php:
    container_name: 'php'
    image: php:7.2-apache
    ports:
      - '18080:80'
    volumes:
      - .:/var/www/html
